In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [2]:
arr1 = np.arange(9).reshape(3,3)

In [3]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [7]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
ser1=Series([0,1,2],index=['T','U','V'])
ser1

T    0
U    1
V    2
dtype: int64

In [10]:
ser2=Series([3,4],index=['X','Y'])

In [11]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [14]:
pd.concat([ser1,ser2],axis=1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [15]:
pd.concat([ser1,ser2],keys=[
    'cat1','cat2'
])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [16]:
dframe1 = DataFrame(np.random.randn(4,3),columns=['X','Y','Z'])

In [17]:
dframe1

X         Y         Z
0 -2.720160 -2.485122 -0.355506
1 -0.001121  0.089883 -0.135795
2 -0.737906 -0.642903 -0.919820
3 -1.108478  0.700215 -1.213238

In [18]:
dframe2 = DataFrame(np.random.randn(3,3),columns=['Y','Q','X'])

In [19]:
dframe2

Y         Q         X
0 -0.698335  0.259415 -0.252573
1  1.590008 -0.836869  1.378265
2 -0.136494  0.235598  0.164665

In [23]:
pd.concat([dframe1,dframe2])

X         Y         Z         Q
0 -2.720160 -2.485122 -0.355506       NaN
1 -0.001121  0.089883 -0.135795       NaN
2 -0.737906 -0.642903 -0.919820       NaN
3 -1.108478  0.700215 -1.213238       NaN
0 -0.252573 -0.698335       NaN  0.259415
1  1.378265  1.590008       NaN -0.836869
2  0.164665 -0.136494       NaN  0.235598