In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [3]:
dframe = DataFrame(np.arange(16).reshape(4,4))

In [4]:
dframe

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [6]:
t=np.random.rand(2)

In [7]:
t+t

array([1.12527065, 1.64015955])

In [9]:
m=np.random.randn(4)

In [11]:
t=m+m

In [13]:
np.sum(t)

1.7628379923109427

In [14]:
np.sum(dframe)

0    24
1    28
2    32
3    36
dtype: int64

In [15]:
np.min(dframe)

0    0
1    1
2    2
3    3
dtype: int32

In [16]:
dframe.max()

0    12
1    13
2    14
3    15
dtype: int32

In [17]:
dframe.cumsum()

0   1   2   3
0   0   1   2   3
1   4   6   8  10
2  12  15  18  21
3  24  28  32  36

In [26]:
blender = np.random.permutation(4)

In [27]:
# this np.random.permutation is used to permutate the dataframe
blender

array([2, 3, 1, 0])

In [28]:
dframe.take(blender)

0   1   2   3
2   8   9  10  11
3  12  13  14  15
1   4   5   6   7
0   0   1   2   3

In [29]:
from random import randint

In [30]:
randint(10,100)

36

In [31]:
box = np.array([1,2,3])

In [32]:
shaker = np.random.randint(0,len(box),10)

In [33]:
shaker

array([1, 1, 0, 1, 1, 0, 2, 1, 0, 0])

In [34]:
box.take(shaker)

array([2, 2, 1, 2, 2, 1, 3, 2, 1, 1])

In [35]:
dframe1 = DataFrame(np.arange(16).reshape(4,4),index=['SF','LA','IN','TN'],columns=['A','B','C','D'])

In [36]:
dframe1

A   B   C   D
SF   0   1   2   3
LA   4   5   6   7
IN   8   9  10  11
TN  12  13  14  15

In [37]:
dframe1.A

SF     0
LA     4
IN     8
TN    12
Name: A, dtype: int32

In [39]:
dframe1.A['SF']

0

In [40]:
dframe.dropna()

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [41]:
dframe1.A= np.nan

In [42]:
dframe1

A   B   C   D
SF NaN   1   2   3
LA NaN   5   6   7
IN NaN   9  10  11
TN NaN  13  14  15

In [45]:
dframe1.dropna(axis=1)

B   C   D
SF   1   2   3
LA   5   6   7
IN   9  10  11
TN  13  14  15

In [46]:
dframe1

A   B   C   D
SF NaN   1   2   3
LA NaN   5   6   7
IN NaN   9  10  11
TN NaN  13  14  15

In [47]:
dframe1.fillna(1)

A   B   C   D
SF  1.0   1   2   3
LA  1.0   5   6   7
IN  1.0   9  10  11
TN  1.0  13  14  15